services:
  backend:
    image: "g27-backend"
    container_name: "backend"
    depends_on:
      - "mongo"
    ports:
      - "5000:3000"
  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    ports:
      - "27017:27017"